{
 "title": "Dominios .BR",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Grupo", "query": "*" },
   { "name": "host", "label": "Host", "query": "$group.*" },
   { "name": "dominio", "label": "Dominio", "query": "$group.$host.DominiosBR.*" },
   { "name": "tecnico", "label": "Tecnico", "query": "$group.$host.DominiosBR.*" },
   { "name": "administrativo", "query": "$group.$host.DominiosBR.*" },
   { "name": "titular", "query": "$group.$host.DominiosBR.*" },
   { "name": "dns1", "query": "$group.$host.DominiosBR.*" },
   { "name": "dns2", "query": "$group.$host.DominiosBR.*" },
   { "name": "expire", "query": "$group.$host.DominiosBR.*" }
  ]
 },
 "panels": [
  {
   "title": "Contato Administrativo",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "DominiosBR" },
     "group": { "filter": "Home" },
     "host": { "filter": "Monitoramento" },
     "item": { "filter": "$administrativo" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Contato Tecnico",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "DominiosBR" },
     "group": { "filter": "Home" },
     "host": { "filter": "Monitoramento" },
     "item": { "filter": "$tecnico" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Titular",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "DominiosBR" },
     "group": { "filter": "Home" },
     "host": { "filter": "Monitoramento" },
     "item": { "filter": "$titular" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS Primário",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "DominiosBR" },
     "group": { "filter": "Home" },
     "host": { "filter": "Monitoramento" },
     "item": { "filter": "$dns1" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "DNS Secundário",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "DominiosBR" },
     "group": { "filter": "Home" },
     "host": { "filter": "Monitoramento" },
     "item": { "filter": "$dns2" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo para expiração",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "application": { "filter": "DominiosBR" },
     "group": { "filter": "Home" },
     "host": { "filter": "Monitoramento" },
     "item": { "filter": "$expire" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}